version: "3.8"
services:
  oauth2-proxy:
    image: "bitnami/oauth2-proxy:5.1.1-debian-10-r27"
    command: >
      '--http-address=0.0.0.0:4180'
      '--provider=oidc'
      '--redirect-url=http://localhost/oauth2/callback'
      '--cookie-secret=secret'
      '--cookie-secure=false'
      '--email-domain=["kaito2.example.com"]'
      '--oidc-issuer-url=${ISSUER_URL}'
      '--client-id=${CLIENT_ID}'
      '--client-secret=${CLIENT_SECRET}'
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - oauth2-proxy
    restart: "always"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    command: "nginx"
