[tox]
isolated_build = true
envlist = py38, flake8-py3

[testenv:py38]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest tests/

[testenv:flake8-py3]
whitelist_externals = poetry
skip_install = true
commands =
    poetry install -v
    poetry run flake8 --version
    poetry run flake8 tox_sample tests
